export const resDetail = {
  success: true,
  message: '요청에 성공하였습니다.',
  data: {
    diaryId: 8,
    uid: 5,
    condition: 2,
    name: '닉네임11',
    content: '4',
    myHeart: false,
    symptomList: [
      {
        symptomId: 1,
        symptomName: '어지러움',
        score: 10,
      },
      {
        symptomId: 2,
        symptomName: '두통',
        score: 20,
      },
    ],
    images: [],
    comments: [
      {
        commentId: 2,
        uid: 5,
        likeCount: 0,
        declarationCount: 0,
        name: '닉네임11',
        content: '힘내세요!!',
        createdDate: '20230205',
        myHeart: false,
        condition: 0,
      },
      {
        commentId: 3,
        uid: 5,
        likeCount: 0,
        declarationCount: 0,
        name: '닉네임11',
        content: '힘내세요!!',
        createdDate: '20230205',
        myHeart: false,
        condition: 0,
      },
      {
        commentId: 4,
        uid: 5,
        likeCount: 0,
        declarationCount: 0,
        name: '닉네임11',
        content: '힘내세요!!',
        createdDate: '20230205',
        myHeart: false,
        condition: 0,
      },
    ],
  },
};
