export const resDetail = {
  success: true,
  message: '요청에 성공하였습니다.',
  data: {
    diaryId: 8,
    uid: 5,
    title: '제목',
    condition: 2,
    name: '닉네임11',
    content: '4',
    myHeart: false,
    createdAt: '2023-02-03 07:02:53',
    symptomList: [
      {
        symptomId: 1,
        symptomName: '어지러움',
        score: 10,
      },
      {
        symptomId: 2,
        symptomName: '두통',
        score: 7,
      },
    ],
    images: [],
    comments: [
      {
        commentId: 2,
        uid: 5,
        likeCount: 0,
        declarationCount: 0,
        name: '닉네임11',
        content: '힘내세요!!',
        createdAt: '2023-02-05 07:02:53',
        myHeart: false,
        condition: 0,
      },
      {
        commentId: 3,
        uid: 5,
        likeCount: 0,
        declarationCount: 0,
        name: '닉네임11',
        content: '힘내세요!!',
        createdAt: '2023-02-04 07:02:53',
        myHeart: false,
        condition: 0,
      },
      {
        commentId: 4,
        uid: 5,
        likeCount: 0,
        declarationCount: 0,
        name: '닉네임11',
        content: '힘내세요!!',
        createdAt: '2023-02-01 07:02:53',
        myHeart: false,
        condition: 0,
      },
    ],
  },
};
