export const resDetail = {
  success: true,
  message: '요청에 성공하였습니다.',
  data: {
    diaryId: 8,
    userId: 0,
    userStatus: 1,
    likeCount: 0,
    commentCount: 0,
    title: '일기장테스트1',
    name: '졸린무지',
    content:
      '일기test 일기test 일기test 일기test 일기test 일기test 일기test 일기test 일기test 일기test 일기test 일기test 일기test 일기test 일기test ',
    uid: 'user13',
    createdAt: '2023-02-03 07:13:47',
    condition: '2',
    myHeart: false,
    symptomList: [
      {
        symptomId: 1,
        symptomName: '어지러움',
        score: 10,
      },
      {
        symptomId: 2,
        symptomName: '두통',
        score: 7,
      },
    ],
    images: [],
    comments: [
      {
        commentId: 2,
        userId: 5,
        likeCount: 0,
        declarationCount: 0,
        uid: 'user11',
        name: '닉네임11',
        content: '힘내세요!!',
        createdAt: '2023-02-03 08:52:56',
        myHeart: false,
        userStatus: 0,
        condition: 1,
      },
      {
        commentId: 3,
        userId: 5,
        likeCount: 0,
        declarationCount: 0,
        uid: 'user11',
        name: '닉네임11',
        content: '힘내세요!!',
        createdAt: '2023-02-03 08:52:57',
        myHeart: false,
        userStatus: 0,
        condition: 1,
      },
      {
        commentId: 4,
        userId: 5,
        likeCount: 1,
        declarationCount: 0,
        uid: 'user11',
        name: '닉네임11',
        content: '힘내세요!!',
        createdAt: '2023-02-03 08:52:58',
        myHeart: false,
        userStatus: 0,
        condition: 1,
      },
    ],
  },
};
