export const res = {
  success: true,
  status: 200,
  message: '요청에 성공하였습니다.',
  data: [
    {
      paperId: 9,
      title: '제목',
      name: '닉네임이최대열자예요',
      content:
        '일기내용블라블라어떻게 하나요? 블라블라 Most fonts have a particular weight which corresponds to one of the numbers in Common weight name mapping. However some fonts, called variablethe chosen weight.',
      commentCount: 0,
      likeCount: 0,
      date: '2023-02-01-16-21-40',
      condition: 0,
      open: true,
      images: ['url', 'url2'],
      symptomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 8,
      title: '제목',
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: '20230125',
      condition: 1,
      open: true,
      images: ['url', 'url2'],
      symptomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 7,
      title: '제목',
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: '20230124',
      condition: 3,
      open: true,
      images: ['url', 'url2'],
      symptomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 6,
      title: '제목',
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: null,
      condition: 4,
      open: true,
      images: ['url', 'url2'],
      symptomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 5,
      title: '제목',
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: '20230125',
      condition: 1,
      open: true,
      images: ['url', 'url2'],
      symptomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 4,
      title: '제목',
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: '20230124',
      condition: 3,
      open: true,
      images: ['url', 'url2'],
      symptomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 3,
      title: '제목',
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: null,
      condition: 4,
      open: true,
      images: ['url', 'url2'],
      symptomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 2,
      title: '제목',
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: '20230125',
      condition: 1,
      open: true,
      images: ['url', 'url2'],
      symptomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 1,
      title: '제목',
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: '20230124',
      condition: 3,
      open: true,
      images: ['url', 'url2'],
      symptomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 0,
      title: '제목',
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: null,
      condition: 4,
      open: true,
      images: ['url', 'url2'],
      symptomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
  ],
};
