export const res = {
  success: true,
  status: 200,
  message: '요청에 성공하였습니다.',
  data: [
    {
      paperId: 9,
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: '20230126',
      condition: 0,
      open: true,
      images: ['url', 'url2'],
      symtomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 8,
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: '20230125',
      condition: 1,
      open: true,
      images: ['url', 'url2'],
      symtomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 7,
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: '20230124',
      condition: 3,
      open: true,
      images: ['url', 'url2'],
      symtomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 6,
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: null,
      condition: 4,
      open: true,
      images: ['url', 'url2'],
      symtomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 5,
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: '20230125',
      condition: 1,
      open: true,
      images: ['url', 'url2'],
      symtomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 4,
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: '20230124',
      condition: 3,
      open: true,
      images: ['url', 'url2'],
      symtomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 3,
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: null,
      condition: 4,
      open: true,
      images: ['url', 'url2'],
      symtomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 2,
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: '20230125',
      condition: 1,
      open: true,
      images: ['url', 'url2'],
      symtomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 1,
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: '20230124',
      condition: 3,
      open: true,
      images: ['url', 'url2'],
      symtomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
    {
      paperId: 0,
      name: '닉네임',
      content: '일기내용블라블라',
      commentCount: 0,
      likeCount: 0,
      date: null,
      condition: 4,
      open: true,
      images: ['url', 'url2'],
      symtomList: [
        {
          symptomId: 1,
          symptomName: '어지러움',
          score: 10,
        },
        {
          symptomId: 2,
          symptomName: '두통',
          score: 20,
        },
      ],
    },
  ],
};
